-- QOS Web Service Schema

DROP TABLE IF EXISTS TB_ALARM;
DROP TABLE IF EXISTS TB_LOG;
DROP TABLE IF EXISTS TB_ALGORITHM;
DROP TABLE IF EXISTS TB_QUALITY;
DROP TABLE IF EXISTS TB_STORAGE_SPACE_POLICY;
DROP TABLE IF EXISTS TB_STORAGE_DELETE_TARGET;
DROP TABLE IF EXISTS TB_STORAGE_RETENTION_POLICY;

CREATE TABLE TB_QUALITY (
    ID       SERIAL        NOT NULL,
    NAME     VARCHAR(100)  NOT NULL,
    STATUS   VARCHAR(20)   NOT NULL DEFAULT '대기',
    PROGRESS INT           NOT NULL DEFAULT 0,
    REG_DT   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_QUALITY PRIMARY KEY (ID)
);

CREATE TABLE TB_ALGORITHM (
    ID      SERIAL       NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    TYPE    VARCHAR(50)  NOT NULL,
    ENABLED CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ALGORITHM PRIMARY KEY (ID)
);

CREATE TABLE TB_LOG (
    ID      SERIAL        NOT NULL,
    LEVEL   VARCHAR(10)   NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL,
    REG_DT  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_LOG PRIMARY KEY (ID)
);

CREATE TABLE TB_ALARM (
    ID       SERIAL       NOT NULL,
    TYPE     VARCHAR(100) NOT NULL,
    TARGET   VARCHAR(100) NOT NULL,
    SEVERITY VARCHAR(20)  NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL DEFAULT '미처리',
    REG_DT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ALARM PRIMARY KEY (ID)
);

CREATE TABLE TB_STORAGE_DELETE_TARGET (
    ID              SERIAL        NOT NULL,
    TARGET_NAME     VARCHAR(100)  NOT NULL,
    DELETE_MODE     VARCHAR(20)   NOT NULL,
    TARGET_TYPE     VARCHAR(20)   NOT NULL,
    BASE_PATH       VARCHAR(500)  NOT NULL,
    FILE_PATTERN    VARCHAR(100),
    FILE_EXTENSION  VARCHAR(30),
    MIN_AGE_DAYS    INT,
    MIN_SIZE_BYTES  BIGINT,
    ENABLED         CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION     VARCHAR(1000),
    REG_DT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_DELETE_TARGET PRIMARY KEY (ID),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_MODE CHECK (DELETE_MODE IN ('AUTO', 'MANUAL')),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_TYPE CHECK (TARGET_TYPE IN ('FILE', 'RULE')),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IX_TB_STORAGE_DELETE_TARGET_01
    ON TB_STORAGE_DELETE_TARGET (DELETE_MODE, TARGET_TYPE, ENABLED);

CREATE TABLE TB_STORAGE_RETENTION_POLICY (
    ID              SERIAL        NOT NULL,
    FILE_TYPE_NAME  VARCHAR(100)  NOT NULL,
    FILE_EXTENSION  VARCHAR(30)   NOT NULL,
    RETENTION_DAYS  INT           NOT NULL,
    ENABLED         CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION     VARCHAR(1000),
    REG_DT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_RETENTION_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_STORAGE_RETENTION_POLICY_01 UNIQUE (FILE_EXTENSION),
    CONSTRAINT CK_TB_STORAGE_RETENTION_POLICY_DAYS CHECK (RETENTION_DAYS BETWEEN 1 AND 3650),
    CONSTRAINT CK_TB_STORAGE_RETENTION_POLICY_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IX_TB_STORAGE_RETENTION_POLICY_01
    ON TB_STORAGE_RETENTION_POLICY (ENABLED, FILE_EXTENSION);

CREATE TABLE TB_STORAGE_SPACE_POLICY (
    ID                SERIAL        NOT NULL,
    TARGET_PATH       VARCHAR(500)  NOT NULL,
    WARNING_PERCENT   DECIMAL(5,2)  NOT NULL DEFAULT 80.00,
    DANGER_PERCENT    DECIMAL(5,2)  NOT NULL DEFAULT 90.00,
    MIN_FREE_BYTES    BIGINT,
    ENABLED           CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION       VARCHAR(1000),
    REG_DT            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT            TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_SPACE_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_STORAGE_SPACE_POLICY_01 UNIQUE (TARGET_PATH),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_PERCENT CHECK (
        WARNING_PERCENT >= 0
        AND WARNING_PERCENT < DANGER_PERCENT
        AND DANGER_PERCENT <= 100
    ),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_MIN_FREE CHECK (MIN_FREE_BYTES IS NULL OR MIN_FREE_BYTES >= 0),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IX_TB_STORAGE_SPACE_POLICY_01
    ON TB_STORAGE_SPACE_POLICY (ENABLED, TARGET_PATH);

INSERT INTO TB_STORAGE_SPACE_POLICY
    (TARGET_PATH, WARNING_PERCENT, DANGER_PERCENT, MIN_FREE_BYTES, ENABLED, DESCRIPTION)
VALUES
    ('ALL', 80.00, 90.00, NULL, 'Y', '전체 저장장치 공통 가용 공간 기준');
