-- QOS Web Service Schema

DROP TABLE IF EXISTS TB_ALARM;
DROP TABLE IF EXISTS TB_LOG;
DROP TABLE IF EXISTS TB_ALGORITHM;
DROP TABLE IF EXISTS TB_QUALITY;

CREATE TABLE TB_QUALITY (
    ID       SERIAL        NOT NULL,
    NAME     VARCHAR(100)  NOT NULL,
    STATUS   VARCHAR(20)   NOT NULL DEFAULT '대기',
    PROGRESS INT           NOT NULL DEFAULT 0,
    REG_DT   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_QUALITY PRIMARY KEY (ID)
);

CREATE TABLE TB_ALGORITHM (
    ID      SERIAL       NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    TYPE    VARCHAR(50)  NOT NULL,
    ENABLED CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ALGORITHM PRIMARY KEY (ID)
);

CREATE TABLE TB_LOG (
    ID      SERIAL        NOT NULL,
    LEVEL   VARCHAR(10)   NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL,
    REG_DT  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_LOG PRIMARY KEY (ID)
);

CREATE TABLE TB_ALARM (
    ID       SERIAL       NOT NULL,
    TYPE     VARCHAR(100) NOT NULL,
    TARGET   VARCHAR(100) NOT NULL,
    SEVERITY VARCHAR(20)  NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL DEFAULT '미처리',
    REG_DT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ALARM PRIMARY KEY (ID)
);
