CREATE TABLE IF NOT EXISTS TB_STORAGE_RETENTION_POLICY (
    ID              SERIAL        NOT NULL,
    FILE_TYPE_NAME  VARCHAR(100)  NOT NULL,
    FILE_EXTENSION  VARCHAR(30)   NOT NULL,
    RETENTION_DAYS  INT           NOT NULL,
    ENABLED         CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION     VARCHAR(1000),
    REG_DT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_RETENTION_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_STORAGE_RETENTION_POLICY_01 UNIQUE (FILE_EXTENSION),
    CONSTRAINT CK_TB_STORAGE_RETENTION_POLICY_DAYS CHECK (RETENTION_DAYS BETWEEN 1 AND 3650),
    CONSTRAINT CK_TB_STORAGE_RETENTION_POLICY_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IF NOT EXISTS IX_TB_STORAGE_RETENTION_POLICY_01
    ON TB_STORAGE_RETENTION_POLICY (ENABLED, FILE_EXTENSION);

INSERT INTO TB_STORAGE_RETENTION_POLICY
    (FILE_TYPE_NAME, FILE_EXTENSION, RETENTION_DAYS, ENABLED, DESCRIPTION)
SELECT 'Dump 파일', 'dump', 7, 'Y', '수동 삭제 테스트 dump 파일 기본 보관 기간'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_RETENTION_POLICY WHERE FILE_EXTENSION = 'dump'
);

INSERT INTO TB_STORAGE_RETENTION_POLICY
    (FILE_TYPE_NAME, FILE_EXTENSION, RETENTION_DAYS, ENABLED, DESCRIPTION)
SELECT 'Log 파일', 'log', 30, 'Y', '로그 파일 자동 삭제 기준 보관 기간'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_RETENTION_POLICY WHERE FILE_EXTENSION = 'log'
);

INSERT INTO TB_STORAGE_RETENTION_POLICY
    (FILE_TYPE_NAME, FILE_EXTENSION, RETENTION_DAYS, ENABLED, DESCRIPTION)
SELECT '임시 파일', 'tmp', 3, 'Y', '임시 파일 보관 기간'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_RETENTION_POLICY WHERE FILE_EXTENSION = 'tmp'
);

INSERT INTO TB_STORAGE_RETENTION_POLICY
    (FILE_TYPE_NAME, FILE_EXTENSION, RETENTION_DAYS, ENABLED, DESCRIPTION)
SELECT 'CSV 파일', 'csv', 90, 'Y', '통계 및 이력 CSV 산출물 보관 기간'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_RETENTION_POLICY WHERE FILE_EXTENSION = 'csv'
);
