CREATE TABLE IF NOT EXISTS TB_STORAGE_SPACE_POLICY (
    ID                SERIAL        NOT NULL,
    TARGET_PATH       VARCHAR(500)  NOT NULL,
    WARNING_PERCENT   DECIMAL(5,2)  NOT NULL DEFAULT 80.00,
    DANGER_PERCENT    DECIMAL(5,2)  NOT NULL DEFAULT 90.00,
    MIN_FREE_BYTES    BIGINT,
    ENABLED           CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION       VARCHAR(1000),
    REG_DT            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT            TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_SPACE_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_STORAGE_SPACE_POLICY_01 UNIQUE (TARGET_PATH),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_PERCENT CHECK (
        WARNING_PERCENT >= 0
        AND WARNING_PERCENT < DANGER_PERCENT
        AND DANGER_PERCENT <= 100
    ),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_MIN_FREE CHECK (MIN_FREE_BYTES IS NULL OR MIN_FREE_BYTES >= 0),
    CONSTRAINT CK_TB_STORAGE_SPACE_POLICY_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IF NOT EXISTS IX_TB_STORAGE_SPACE_POLICY_01
    ON TB_STORAGE_SPACE_POLICY (ENABLED, TARGET_PATH);

INSERT INTO TB_STORAGE_SPACE_POLICY
    (TARGET_PATH, WARNING_PERCENT, DANGER_PERCENT, MIN_FREE_BYTES, ENABLED, DESCRIPTION)
SELECT 'ALL', 80.00, 90.00, NULL, 'Y', '전체 저장장치 공통 가용 공간 기준'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_SPACE_POLICY WHERE TARGET_PATH = 'ALL'
);
