CREATE TABLE IF NOT EXISTS TB_STORAGE_DELETE_TARGET (
    ID              SERIAL        NOT NULL,
    TARGET_NAME     VARCHAR(100)  NOT NULL,
    DELETE_MODE     VARCHAR(20)   NOT NULL,
    TARGET_TYPE     VARCHAR(20)   NOT NULL,
    BASE_PATH       VARCHAR(500)  NOT NULL,
    FILE_PATTERN    VARCHAR(100),
    FILE_EXTENSION  VARCHAR(30),
    MIN_AGE_DAYS    INT,
    MIN_SIZE_BYTES  BIGINT,
    ENABLED         CHAR(1)       NOT NULL DEFAULT 'Y',
    DESCRIPTION     VARCHAR(1000),
    REG_DT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_STORAGE_DELETE_TARGET PRIMARY KEY (ID),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_MODE CHECK (DELETE_MODE IN ('AUTO', 'MANUAL')),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_TYPE CHECK (TARGET_TYPE IN ('FILE', 'RULE')),
    CONSTRAINT CK_TB_STORAGE_DELETE_TARGET_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE INDEX IF NOT EXISTS IX_TB_STORAGE_DELETE_TARGET_01
    ON TB_STORAGE_DELETE_TARGET (DELETE_MODE, TARGET_TYPE, ENABLED);

INSERT INTO TB_STORAGE_DELETE_TARGET
    (TARGET_NAME, DELETE_MODE, TARGET_TYPE, BASE_PATH, FILE_PATTERN, FILE_EXTENSION,
     MIN_AGE_DAYS, MIN_SIZE_BYTES, ENABLED, DESCRIPTION)
SELECT '수동 삭제 테스트 dump 파일', 'MANUAL', 'RULE', 'D:\deleteTest\', '*.dump', 'dump',
       NULL, NULL, 'Y', '저장장치 관리 화면에서 수동으로 선택 삭제할 테스트 파일 기준'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_DELETE_TARGET WHERE TARGET_NAME = '수동 삭제 테스트 dump 파일'
);

INSERT INTO TB_STORAGE_DELETE_TARGET
    (TARGET_NAME, DELETE_MODE, TARGET_TYPE, BASE_PATH, FILE_PATTERN, FILE_EXTENSION,
     MIN_AGE_DAYS, MIN_SIZE_BYTES, ENABLED, DESCRIPTION)
SELECT '30일 경과 로그 자동 삭제 기준', 'AUTO', 'RULE', 'D:\deleteTest\logs\', '*.log', 'log',
       30, NULL, 'Y', '자동 삭제 배치가 참조할 로그 파일 분류 기준'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_DELETE_TARGET WHERE TARGET_NAME = '30일 경과 로그 자동 삭제 기준'
);

INSERT INTO TB_STORAGE_DELETE_TARGET
    (TARGET_NAME, DELETE_MODE, TARGET_TYPE, BASE_PATH, FILE_PATTERN, FILE_EXTENSION,
     MIN_AGE_DAYS, MIN_SIZE_BYTES, ENABLED, DESCRIPTION)
SELECT '대용량 임시 파일 수동 점검', 'MANUAL', 'RULE', 'D:\deleteTest\', '*.tmp', 'tmp',
       NULL, 104857600, 'Y', '100MB 이상 임시 파일을 수동 삭제 대상으로 조회'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_STORAGE_DELETE_TARGET WHERE TARGET_NAME = '대용량 임시 파일 수동 점검'
);
